#!/usr/bin/with-contenv bash

# Get our docker runtimes
RUNTIMES=$(docker info | grep Runtimes)

# If we have nvidia runtimes we start gpu workers
if [[ $RUNTIMES == *"nvidia"* ]]; then
    export HOST_DATA_BIND=$(docker inspect --format='{{ index .HostConfig.Binds  0  }}' idmtools_workers)
    echo "NVIDIA Docker Detected"
    echo "Start GPU Workers"
    # TODO Detect number of gpus and start right amount of workers
    # This launches the workers that do all the actual gpu run task work
    exec s6-setuidgid idmtools /usr/local/bin/dramatiq idmtools_platform_local.internals.workers.run_broker:redis_broker idmtools_platform_local.internals.workers.run --processes 1 --threads 1 --queues gpu
fi