# See https://github.com/gorakhargosh/watchdog
tricks:
- watchdog.tricks.ShellCommandTrick:
    patterns: ["*.py"]
    shell_command: "pymake lint"
    wait_for_process: true
    drop_during_process: true
- watchdog.tricks.ShellCommandTrick:
    patterns: ["*.py"]
    shell_command: "pymake test"
    drop_during_process: true