#!/usr/bin/with-contenv bash
export HOST_DATA_BIND=$(docker inspect --format='{{ index .HostConfig.Binds  0  }}' idmtools_workers)
echo Starting CPU Workers
# This launches the workers that do all the actual run task work
exec s6-setuidgid idmtools /usr/local/bin/dramatiq idmtools_platform_local.internals.workers.run_broker:redis_broker idmtools_platform_local.internals.workers.run --queues cpu --threads 1