site_name: idmtools
site_url: https://docs.idmod.org/idmtools/
site_description: Python tools for streamlining disease modeling workflows on HPC clusters
site_author: Institute for Disease Modeling

# Repository
repo_url: https://github.com/InstituteforDiseaseModeling/idmtools
repo_name: InstituteforDiseaseModeling/idmtools
edit_uri: edit/main/docs/

# Configuration
docs_dir: docs
site_dir: site

theme:
  name: material
  custom_dir: docs/customization/overrides
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/idm-logo-transparent.png
  favicon: images/favicon.ico
  features:
    - navigation.footer # include a footer with links to privacy, terms, etc.
    - content.code.copy # enable copy buttons for code blocks
    - navigation.indexes # enable parent index page for sections
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: light blue
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: light blue

  icon:
    repo: fontawesome/brands/github
    logo: material/dna

# Navigation
nav:
  - Home: index.md
  - What's new: whatsnew.md
  - Getting started:
    - getting-started/index.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quick start: getting-started/quickstart.md

  - User guide:
    - user-guide/index.md
    - Creating simulations and experiments: user-guide/creating-simulations.md
    - Asset management: user-guide/assets.md
    - Parameter sweeps: tutorials/parameter-sweeps.md
    - Data analysis: data-analysis/index.md

  - Tutorials:
    - tutorials/index.md
    - Python models: tutorials/python-models.md
    - Running sweeps: tutorials/parameter-sweeps.md
    - Singularity containers: tutorials/singularity.md
    - Filter simulations: tutorials/filter-simulations.md
    - Data analysis: data-analysis/index.md

  - Platforms:
    - platforms/index.md
    - COMPS: platforms/comps.md
    - Slurm: platforms/slurm.md
    - Container: platforms/container.md
  - API:
    - api/index.md
    - Core: api/core.md
    - Models: api/models.md
    - Platforms: api/platforms.md
    - Data analysis:
      - data-analysis/index.md
      - Analyzers: data-analysis/analyzers.md
      - Analyze manager: data-analysis/analyze-manager.md
      - Platform analysis: data-analysis/platform-analysis.md

  - CLI reference:
    - cli/index.md

  - FAQ: faq/index.md

  - Quick reference: quick_ref.md

  - Development:
    - Release process: development/release-process.md

# icons, semantic markup, emojis
markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list # enables HTMl and CSS classes to inline elements
  - md_in_html # enables grids
  - admonition # warnings, etc.
  - def_list
  - pymdownx.emoji: # emojis and icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex: # Latex processing for math equations
      generic: true
  - pymdownx.snippets: # insert content from other files
      auto_append:
        - docs/includes/glossary.md # definitions for glossary entries
  - abbr # term/abbreviation hover descriptions
  - pymdownx.blocks.details: # allows nesting of collapsible code
  - pymdownx.highlight: # syntax highlighting for code blocks
      linenums: true
      default_lang: 'python'
  - pymdownx.inlinehilite # syntax highlighting for inline code
  - pymdownx.superfences # enables code, diagram fences to be nested in lists, etc.e
  - pymdownx.details # collapsible elements
  - pymdownx.tabbed: # tabbed content that can be toggled
      alternate_style: true
  - pymdownx.blocks.caption # captions for images, tables, etc.

# javascript and CSS customization
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - customization/css/extra.css # custom CSS for footer spacing

plugins:
  - search # search functionality
  - autorefs # automatically create linkable references
  - include-markdown # include other files, such as READMEs
  - table-reader # enables rendering of CSV/TSV files as tables
  - mermaid2 # enables mermaid diagrams inserted as text
  - mkdocs-jupyter: # enables Jupyter notebooks to be rendered
      execute: true
      allow_errors: false # set to true to continue executing cells even if one fails
      include_source: true
  # - api-autonav: API reference currently manually written
  #     modules: ['idmtools_core'] # provide path to package
  #     module_options: {}
  #     nav_section_title: "API reference"
  #     api_root_uri: "reference"
  #     nav_item_prefix: "<code class='doc-symbol doc-symbol-nav doc-symbol-module'></code>"
  #     exclude_private: true
  #     show_full_namespace: false
  #     on_implicit_namespace_package: "warn"
  # - mkdocstrings: # process docstrings to generate API reference
  #     handlers:
  #       python:
  #         paths: [src] # path to source code
  #         options:
  #           docstring_style: google
  #           show_source: false
  #           merge_init_into_class: true
  #           heading_level: 2
  #           show_symbol_type_heading: true
  #           show_symbol_type_toc: true
  #           show_root_toc_entry: true
  #           show_object_full_path: true
# Copyright
copyright: Copyright &copy; 2019-2026 Gates Foundation. All rights reserved.


extra:
  generator: false
  footer_links:
    - text: "Privacy and Cookies Notice"
      href: "https://www.gatesfoundation.org/Privacy-and-Cookies-Notice"
    - text: "Terms of Use"
      href: "https://www.gatesfoundation.org/Terms-of-Use"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InstituteforDiseaseModeling/idmtools # update to your repo
    - icon: fontawesome/regular/envelope
      link: mailto:idm@gatesfoundation.org
    - icon: octicons/globe-24
      link: https://idmod.org
    - icon: simple/youtube
      link: http://www.youtube.com/@institutefordiseasemodelin1987
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/institute-disease-modeling

  analytics:
    provider: custom
    tracking_id: GTM-NK4K647
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! If you like, provide additional information by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
