# We have to use version 2 formatting of docker-compose to allow use to limit resource usage
version: "2.3"
services:
  linuxtst:
    build:
      context: .
    # We parameterize the build so we can easily specify our desired docker image name
    # ie docker-compose
    image: "idmtools-linux"
    environment:
      - "CURRENT_UID=${CURRENT_UID:-1000:1000}"
    ports:
      - 5000:5000
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ../../:/idmtools
