HTML_TEST_REPORT ?= comps.test_results.html
# Set comps to high because we mostly just wait on COMPS to finish
PARALLEL_TEST_COUNT ?= 12
# COMPS only has parallel tests
PARALLEL_TESTING = 1
include $(abspath ../../dev_scripts/test_root.mk)