@startuml

class BaseAnalyzer {
    initialize()
    per_experiment()
    filter()
    select_simulation_data()
    finalize()
    destroy()
}

note top of BaseAnalyzer
DTK-Tools
end note

class IAnalyzer {
    initialize()
    per_group()
    filter()
    map()
    reduce()
    destroy()
}

note top of IAnalyzer
idmtools
end note

IAnalyzer -left[hidden]-> BaseAnalyzer

@enduml