@startuml

package "idmtools-core" as registry {
    () "PlatformAPI" as PlatformAPI
}

package "idmtools-platform-comps" as comps {
    [COMPSPlatform]
    [SSMTPlatform]
}

package "COMPS" as COMPS {
    () "pyCOMPSAPI" as pyCOMPSAPI
}


PlatformAPI <-down-- COMPSPlatform: COMPs\nImplementation
PlatformAPI <-- SSMTPlatform: SSMT\nImplementation
COMPSPlatform <--> pyCOMPSAPI
SSMTPlatform <--> pyCOMPSAPI

@enduml