@startuml

[idmtools]
note right of idmtools
Provides plugin infrastructure and
common APIs like Experiments,
Simulations, Suites, Workitems,
Tasks, and Platforms. Also contains
tools for building Simulations in bulk
end note
[idmtools-cli]
note left of [idmtools-cli]
    Provides the CLI for
    idmtools
end note
[idmtools-models]
note right of [idmtools-models]
    Provides common tasks
     for Python and R
end note
[idmtools-platform-comps]
note left of [idmtools-platform-comps]
    Provides ability to
    interact with COMPS
end note
package [idmtools-platform-general] {
    [idmtools-platform-file]
    [idmtools-platform-process]
    }
note left of [idmtools-platform-general]
    Provides folder structures
    for non comps platforms
end note
note left of [idmtools-platform-file]
    Provides folder structures with
    FilePlatform for non COMPS platforms
end note
[idmtools-platform-container]
note right of [idmtools-platform-container]
    Provides ability to run
    locally using Docker containers
end note
[idmtools-platform-slurm]
note right of [idmtools-platform-slurm]
    Provides ability to 
    interact with SLURM
end note

[idmtools-cli] --> [idmtools]
[idmtools-models] --> [idmtools]
[idmtools-platform-comps] -> [idmtools]
[idmtools-platform-general] -> [idmtools]
[idmtools-platform-container] -up-> [idmtools-platform-file]
[idmtools-platform-slurm] -up-> [idmtools-platform-file]
[idmtools-platform-process] -up-> [idmtools-platform-file]:run the process locally
@enduml