version: "3.7"
services:
  redis:
    image: redis:5.0.4-alpine
    volumes:
      - ../data/redis-data:/data
    ports:
      - 6379:6379

  workers:
    build:
      context: .
      #image: idmtools_local.workers
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      # You should only link in the library in development
      #- ./idmtools_local:/app/idmtools_local
      - ../data/workers:/data
    depends_on:
      - redis

# this can be uncommented for development to allow gui for Redis at http://localhost:8081
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

networks:
  default:
    external:
      name: idmtools_network