version: '3'

volumes:
  # This is a dummy volume we only add to control node_modules and prevent it from being coping over locally
  node_modules_client:

services:
  buildenv:
    build:
      context: .
    working_dir: /app

    volumes:
      - "./:/app"
      - node_modules_client:/app/node_modules