[COMMON]
# Maxium number of workers processing in parallel
max_workers = 16

# Maxium batch size to retrieve simulations
batch_size = 20

[COMPS_SLURM]
type = COMPS
endpoint = https://comps.idmod.org
environment = Calculon
priority = Highest
simulation_root = $COMPS_PATH(USER)\output
num_retries = 0
node_group = idm_ab
num_cores = 1
exclusive = False
max_workers = 16
batch_size = 10
