[COMMON]
# Maxium number of workers processing in parallel
max_workers = 16

# Maxium batch size to retrieve simulations
batch_size = 20


[Local]
type = Local
extra1 = 1
extra2 = 2

[COMPS]
type = COMPS
endpoint = https://comps2.idmod.org
environment = Bayesian
priority = Lowest
simulation_root = $COMPS_PATH(USER)\output
node_group = emod_abcd
num_retries = 5
num_cores = 1
exclusive = True

[COMPS_Prod]
type = COMPS
endpoint = https://comps.idmod.org
environment = Belegost
priority = Lowest
simulation_root = $COMPS_PATH(USER)\output
node_group = emod_abcd
num_retries = 0
num_cores = 1
max_workers = 16
batch_size = 10
exclusive = False
test1 = 1
test2 = 2


[COMPSAlt]
type = COMPS
endpoint = https://comps2.idmod.org
environment = Bayesian
priority = Lowest
simulation_root = $COMPS_PATH(USER)\output
node_group = emod_abcd
num_retries = 0
num_cores = 1
max_workers = 16
batch_size = 10
exclusive = False
test1 = 1
test2 = 2

[Logging]
level = DEBUG
console = on

# This is a test we used to validate loading local from section block
[Custom_Local]
type = Local

[Test]
type = Test
num_retries = 5
num_cores = 1

