name: "Rebuild docs"
# curl command from your cmd:
# curl -XPOST -u "username:githubPAT" -H "Accept: application/vnd.github.everest-preview+json" \
# -H "Content-Type: application/json" \
# --data "{\"event_type\": \"master_doc_build\"}" \
#  https://api.github.com/repos/InstituteforDiseaseModeling/idmtools/dispatches
#
# Note, this test will checkout 'dev' branch
on:
  on:
    repository_dispatch:
      # Manually trigger with curl or Postman POST
      types: [master_doc_build]
  push:
    branches:
      # only run this on
      - master
    paths:
      - '**.py'
      - 'docs/**'
  pull_request:
    branches:
      # only run this on
      - master
    paths:
      - '**.py'
      - 'docs/**'
jobs:
  rebuild-documentation:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump version: ')"
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'idmtools'
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('idmtools/docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        working-directory: 'idmtools/docs'
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip py-make
          sudo apt-get install make
          pip install -r requirements.txt
      - name: Install tools in dev mode
        working-directory: 'idmtools'
        run: |
          python dev_scripts/bootstrap.py
      - name: Build docs
        working-directory: 'idmtools/docs'
        run: |
          make html
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: 'gh-pages'
      - name: Copy docs
        run: |
          cp -r idmtools/docs/_build/html/* gh-pages/
          ls -al gh-pages/
      - name: Commit docs
        working-directory: 'gh-pages'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all .
          git commit -m "${{ github.event.head_commit.message }}"
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.DOCS_DEPLOY_KEY }}"
          git push
