# This workflows will download idmtools nightly packages from production artifactory then run tests with curl command
#
# curl command from your cmd:
# curl -XPOST -u "username:githubPAT" -H "Accept: application/vnd.github.everest-preview+json" \
# -H "Content-Type: application/json" \
# --data "{\"event_type\": \"test_release_build\"}" \
#  https://api.github.com/repos/InstituteforDiseaseModeling/idmtools/dispatches
#
# Note, this test will checkout 'master' branch

name: "Install release build and run test"
on:
  repository_dispatch:
    # Manually trigger with above curl or Postman POST
    types: [test_release_build]

jobs:
  install-release-build-run-all-test:
    if: github.repository == 'InstituteforDiseaseModeling/idmtools'
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: download idmtools packages from staging jfrog
        run: |
          pip install idmtools[full] --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
          pip install idmtools-test --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
      - name: login to comps2
        run: |
            python dev_scripts/create_auth_token_args.py --username idmtools_bamboo
      - name: run idmtools_cli tests
        run: |
            cd idmtools_cli/tests
            py.test --durations=3 -v --junitxml=test_results.xml
      - name: Upload idmtools_cli test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_cli_test_results
          path: idmtools_cli/tests/test_results.xml
      - name: run idmtools_core tests
        run: |
            cd idmtools_core/tests
            py.test --durations=3 -v --junitxml=test_results.xml
      - name: Upload idmtools_core test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_core_test_results
          path: idmtools_core/tests/test_results.xml
      - name: run idmtools_models tests
        run: |
            cd idmtools_models/tests
            py.test --durations=3 -v --junitxml=test_results.xml
      - name: Upload idmtools_models test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_models_test_results
          path: idmtools_models/tests/test_results.xml
      - name: run idmtools_platform_comps tests
        run: |
            cd idmtools_platform_comps/tests
            py.test --durations=3 -v --junitxml=test_results.xml
      - name: Upload idmtools_platform_comps test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_platform_comps_test_results
          path: idmtools_platform_comps/tests/test_results.xml
      - name: run idmtools_platform_local tests
        run: |
            cd idmtools_platform_local/tests
            py.test --durations=3 -v --junitxml=test_results.xml
      - name: Upload idmtools_platform_local test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_platform_local_test_results
          path: idmtools_platform_local/tests/test_results.xml