name: "run-release-prod-test"
on: [push, pull_request]

jobs:
  run-release-prod-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
    if: "contains(github.event.head_commit.message, 'Run prod ubuntu all test!')"
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: ${{ matrix.os }} Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Python dependencies
        run: |
          pip install py-make flake8 wheel
      - name: Install dataclass
        if: ${{ matrix.python-version }} == 3.6
        run: |
          pip install dataclasses
      - name: download idmtools packages from production jfrog
        run: |
          pip install idmtools[full] --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
          pip install idmtools-test --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
      - name: login to comps2
        run: |
            python dev_scripts/create_auth_token_args.py --username $COMPS_USER --password $COMPS_PASSWORD
        env:
          COMPS_USER: ${{ secrets.COMPS_USER }}
          COMPS_PASSWORD: ${{ secrets.COMPS_PASSWORD }}
      - name: run idmtools_cli tests
        run: |
            cd idmtools_cli/tests
            py.test --durations=3 -v --junitxml=test_results.xml
      - name: Upload idmtools_cli test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_cli_test_results
          path: idmtools_cli/tests/test_results.xml
      - name: run idmtools_core tests
        run: |
            cd idmtools_core/tests
            py.test --durations=3 -v --junitxml=test_results.xml
      - name: Upload idmtools_core test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_core_test_results
          path: idmtools_core/tests/test_results.xml
      - name: run idmtools_models tests
        run: |
            cd idmtools_models/tests
            py.test --durations=3 -v --junitxml=test_results.xml
      - name: Upload idmtools_models test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_models_test_results
          path: idmtools_models/tests/test_results.xml
      - name: run idmtools_platform_comps tests
        run: |
            cd idmtools_platform_comps/tests
            py.test --durations=3 -v --junitxml=test_results.xml
      - name: Upload idmtools_platform_comps test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_platform_comps_test_results
          path: idmtools_platform_comps/tests/test_results.xml
      - name: run idmtools_platform_local tests
        run: |
            cd idmtools_platform_local/tests
            py.test --durations=3 -v --junitxml=test_results.xml
      - name: Upload idmtools_platform_local test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_platform_local_test_results
          path: idmtools_platform_local/tests/test_results.xml