# install staging packages and run smoke test
# trigger by push or pull_request with commit message: "Run ubuntu smoke test!"

name: "run-smoke-test-ubuntu-stage"
on: [push, pull_request]

jobs:
  run-smoke-test-ubuntu-stage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
    env:
      bamboo_user: ${{ secrets.PYPI_STAGING_USERNAME }}
      bamboo_password: ${{ secrets.PYPI_STAGING_PASSWORD }}
    if: "contains(github.event.head_commit.message, 'Run ubuntu smoke test!')"
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: ${{ matrix.os }} Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Python dependencies
        run: |
          pip install py-make flake8
      - name: Install dataclass
        if: ${{ matrix.python-version }} == 3.6
        run: |
          pip install dataclasses
      - name: download idmtools packages from staging jfrog
        run: |
          pip install idmtools[full] --index-url=https://${{ env.bamboo_user }}:${{ env.bamboo_password }}@packages.idmod.org/api/pypi/pypi-staging/simple
          pip install idmtools-test --index-url=https://${{ env.bamboo_user }}:${{ env.bamboo_password }}@packages.idmod.org/api/pypi/pypi-staging/simple
      - name: login to comps2
        run: |
          python dev_scripts/create_auth_token_args.py --username $COMPS_USER --password $COMPS_PASSWORD
        env:
          COMPS_USER: ${{ secrets.COMPS_USER }}
          COMPS_PASSWORD: ${{ secrets.COMPS_PASSWORD }}
      - name: login to docker staging
        run: |
          echo '${{ env.bamboo_password }}' | docker login idm-docker-staging.packages.idmod.org --username ${{ env.bamboo_user }} --password-stdin
      - name: run idmtools_cli smoke tests
        run: |
          cd idmtools_cli/tests
          py.test --durations=3 -v --junitxml=test_results.xml -m "smoke"
      - name: Upload idmtools_cli smoke test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_cli_test_results
          path: idmtools_cli/tests/test_results.xml
      - name: run idmtools_core smoke tests
        run: |
          cd idmtools_core/tests
          py.test --durations=3 -v --junitxml=test_results.xml -m "smoke"
      - name: Upload idmtools_core smoke test results
        uses: actions/upload-artifact@v2
        if: ${{ success() || failure() }}
        with:
          name: idmtools_core_test_results
          path: idmtools_core/tests/test_results.xml
      - name: run idmtools_models tests
        run: |
          cd idmtools_models/tests
          py.test --durations=3 -v --junitxml=test_results.xml -m "smoke"
      - name: Upload idmtools_models smoke test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_models_test_results
          path: idmtools_models/tests/test_results.xml
      - name: run idmtools_platform_comps tests
        run: |
          cd idmtools_platform_comps/tests
          py.test --durations=3 -v --junitxml=test_results.xml -m "smoke"
      - name: Upload idmtools_platform_comps test results
        uses: actions/upload-artifact@v2
        if: ${{ success() || failure() }}
        with:
          name: idmtools_platform_comps_test_results
          path: idmtools_platform_comps/tests/test_results.xml
      - name: run idmtools_platform_local smoke tests
        run: |
          cd idmtools_platform_local/tests
          py.test --durations=3 -v --junitxml=test_results.xml -m "smoke"
      - name: Upload idmtools_platform_local smoke test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_platform_local_test_results
          path: idmtools_platform_local/tests/test_results.xml