name: Run smoke tests
on: [pull_request]
jobs:
  run-linters:
    name: Run smoke tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make
          pip install black flake8
      - name: Run setup-dev
        run: |
          make setup-dev
      - name: login to comps2
        run: |
            python dev_scripts/create_auth_token_args.py --username shchen
      - name: run smoke tests
        run: |
            make test-smoke
      - name: Upload cli smoke test results
        uses: actions/upload-artifact@v1
        with:
          name: idmtools_cli_test_results
          path: idmtools_cli/tests/test_results.xml
      - name: Upload core smoke test results
        uses: actions/upload-artifact@v1
        with:
          name: idmtools_core_test_results
          path: idmtools_core/tests/test_results.xml
      - name: Upload model smoke test results
        uses: actions/upload-artifact@v1
        with:
          name: idmtools_models_test_results
          path: idmtools_models/tests/test_results.xml
      - name: Upload local platform smoke test results
        uses: actions/upload-artifact@v1
        with:
          name: idmtools_platform_local_test_results
          path: idmtools_platform_local/tests/test_results.xml