# This workflows will upload a Python Package using Twine when a release is created

name: "Staging: idmtools-platform-general"

on:
  push:
    branches:
      # only run this on
      - dev
      - 'release**'
      - main
    paths:
      - 'idmtools_platform_general/**'

jobs:
  deploy-slurm-staging:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump version: ')"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine bump2version
          git config --global user.name "IDM Tools"
          git config --global user.email "idmtools@idmod.org"
      - uses: actions/checkout@v2
      - name: Build and publish
        working-directory: idmtools_platform_general
        env:
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*